name: CI/CD Pipeline (Сборка и деплой)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Проверка стиля кода
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Установка Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Установка flake8 (линтер)
        run: pip install flake8
      - name: Запуск flake8
        run: flake8 app.py --count --show-source --statistics

  test:
    name: Запуск тестов
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Установка Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Установка зависимостей
        run: pip install pytest
      - name: Запуск pytest
        run: pytest

  docker:
    name: Сборка и публикация Docker образа
    needs: [lint, test]  # Зависит от успешного выполнения lint и test
    runs-on: ubuntu-latest
    steps:
      - name: Получение кода
        uses: actions/checkout@v2
      
      - name: Логин в Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Сборка и публикация образа
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/cicd:latest
